// STERIS — Threat Modeling Report Template
// Input variables (passed via `typst compile --input key=value`):
//   title  — report title string
//   data   — absolute path to the threats CSV file

#let report-title = sys.inputs.at("title", default: "Threat Modeling Report")
#let data-path    = sys.inputs.at("data",  default: "threats.csv")

#let threats = csv(data-path, row-type: dictionary)

// ─── Document settings ───────────────────────────────────────────────────────

#set document(title: report-title, date: datetime.today())
#set page(
  paper: "a4",
  margin: (top: 2.5cm, bottom: 2.5cm, left: 2.5cm, right: 2.5cm),
  header: context {
    if counter(page).get().first() > 1 [
      #set text(size: 8pt, fill: luma(130))
      #report-title #h(1fr) STERIS
      #line(length: 100%, stroke: 0.4pt + luma(200))
    ]
  },
  footer: context {
    set text(size: 8pt, fill: luma(130))
    line(length: 100%, stroke: 0.4pt + luma(200))
    h(1fr)
    counter(page).display("1 of 1", both: true)
  },
)
#set text(font: "Liberation Sans", size: 10pt, lang: "en")
#set heading(numbering: "1.")
#show heading.where(level: 1): it => {
  v(0.8em)
  text(size: 14pt, weight: "bold", it)
  v(0.3em)
}
#show heading.where(level: 2): it => {
  v(1em)
  text(size: 11pt, weight: "bold", fill: luma(60), it)
  v(0.2em)
  line(length: 100%, stroke: 0.4pt + luma(200))
  v(0.4em)
}

// ─── Status colour helper ─────────────────────────────────────────────────────

#let status-color(s) = {
  let sl = lower(s)
  if sl == "applicable"     { rgb("#c0392b") }
  else if sl == "mitigated" { rgb("#27ae60") }
  else if sl == "not applicable" { rgb("#7f8c8d") }
  else                      { luma(80) }
}

#let status-badge(s) = box(
  fill: status-color(s),
  inset: (x: 4pt, y: 2pt),
  radius: 3pt,
  text(fill: white, size: 8pt, weight: "bold", upper(s))
)

// ─── Cover page ───────────────────────────────────────────────────────────────

#align(center + horizon)[
  #text(size: 28pt, weight: "bold")[#report-title]
  #v(0.6em)
  #text(size: 12pt, fill: luma(100))[
    Generated by STERIS on #datetime.today().display("[day] [month repr:long] [year]")
  ]
  #v(1.2em)
  #line(length: 60%, stroke: 1pt + luma(180))
  #v(0.6em)
  #text(size: 10pt, fill: luma(130))[Total threats: #threats.len()]
]

#pagebreak()

// ─── Executive summary ────────────────────────────────────────────────────────

= Executive Summary

#let count-status(s) = threats.filter(t => lower(t.at("State", default: "")) == s).len()

#let applicable-count     = count-status("applicable")
#let mitigated-count      = count-status("mitigated")
#let not-applicable-count = count-status("not applicable")

This report documents *#threats.len() threats* identified during the threat modeling activity.

#table(
  columns: (auto, auto),
  stroke: none,
  fill: (_, row) => if calc.odd(row) { luma(245) } else { white },
  inset: (x: 8pt, y: 5pt),
  [*Status*], [*Count*],
  [#status-badge("applicable")],     [#applicable-count],
  [#status-badge("mitigated")],      [#mitigated-count],
  [#status-badge("not applicable")], [#not-applicable-count],
)

#pagebreak()

// ─── Threat catalogue ─────────────────────────────────────────────────────────

= Threat Catalogue

// Threats arrive pre-sorted by Interaction from the generator.
// We iterate with an index and emit a level-2 heading whenever the
// Interaction value changes.

#for (i, threat) in threats.enumerate() {
  let id            = threat.at("Id",           default: "—")
  let name          = threat.at("Title",         default: "—")
  let description   = threat.at("Description",  default: "—")
  let status        = threat.at("State",         default: "—")
  let justification = threat.at("Justification",default: "—")
  let category      = threat.at("Category",      default: "")
  let interaction   = threat.at("Interaction",   default: "")
  let source        = threat.at("Source",        default: "")
  let target        = threat.at("Target",        default: "")

  // Emit a section heading when the interaction group changes
  let prev-interaction = if i > 0 { threats.at(i - 1).at("Interaction", default: "") } else { none }
  if prev-interaction == none or interaction != prev-interaction [
    == #interaction
  ]

  block(
    width: 100%,
    stroke: (left: 3pt + status-color(status), rest: 0.5pt + luma(200)),
    radius: 4pt,
    inset: 10pt,
    below: 1em,
  )[
    #grid(
      columns: (1fr, auto),
      text(weight: "bold", size: 11pt)[#id — #name],
      status-badge(status),
    )
    #v(0.3em)

    #if category != "" or source != "" or target != "" {
      set text(size: 8.5pt, fill: luma(100))
      if category != "" [ *Category:* #category #h(1em) ]
      if source   != "" [ *Source:* #source #h(1em) ]
      if target   != "" [ *Target:* #target ]
      v(0.3em)
    }

    *Description:* #description

    *Justification:* #justification
  ]
}
